version: '3.8'

services:
  omnirecord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omnirecord_dashboard
    ports:
      - "8877:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    network_mode: host
    restart: unless-stopped
